
- name: Initilize Linux Servers
  hosts: [ linux ]
  gather_facts: no
  become: yes
  tasks:
    - name: Configure Hostname
      hostname: 
        name: "{{inventory_hostname}}"

    - name: Install aptitude using apt
      apt: 
        name: aptitude 
        state: latest 
        update_cache: yes
        force_apt_get: yes

    - name: Generate Configuration
      template:
        src: "linux_netplan.j2"
        dest:  "/etc/netplan/60-ntc.yaml"
        mode: 0644
      when: interfaces is defined
      register: netplan

    - name: Apply changes to netplan
      command: netplan apply
      when:
        - interfaces is defined
        - netplan is changed 

    - name: Install Iperf, Iperf3 & nuttcp
      apt:
        name:  "{{ item }}" 
        state: latest 
      loop: [ iperf, iperf3, nuttcp ]

    - name: Install NGINX
      apt:
        name:  nginx
        state: latest 
      when: 
        - "'srv' in inventory_hostname"

    - name: Install docker
      include_role:
        name: install_docker

    - name: Install K6
      include_role:
        name: install_k6
      when: 
        - "'srv' in inventory_hostname"

    - name: Download file to generate Payload
      get_url:
        url: https://wallpaperaccess.com/full/626310.jpg
        dest: /var/www/html/big_image.jpg
      when: 
        - "'srv' in inventory_hostname"

    - name: Generate K6 test file
      template:
        src: "k6.j2"
        dest:  "/tmp/test.j2"
        mode: 0777
      when: 
        - "'srv' in inventory_hostname"

    - name: Install libfontconfig1 (jumphost only)
      apt:
        name:  libfontconfig1
        state: latest 
      when: 
        - "'jump' in inventory_hostname"

